# -*- ruby -*-

require 'hoe'

Hoe.plugins.delete :rubyforge

Hoe.spec 'passw3rd' do
  developer('Neil Matatall', 'neil.matatall@gmail.com')
end

# vim: syntax=ruby

#require 'hoe'
#
#Hoe.plugins.delete :rubyforge
#
#Hoe.spec 'programmatic_crypto' do
#  developer('Neil Matatall', 'neil.matatall@gmail.com')
#end

# vim: syntax=ruby


#require 'rubygems'
#require 'rake'
#require 'rake/clean'
#require 'rake/gempackagetask'
#require 'rake/rdoctask'
#require 'rake/testtask'
#
#
#spec = Gem::Specification.new do |s|
#   s.name = %q{programmatic_crypto}
#   s.version = "0.0.1"
#   s.date = %q{2010-05-26}
#   s.authors = ["Neil Matatall"]
#   s.email = %q{neil.matatall@gmail.com}
#   s.summary = %q{A library for easy crypto mainly aimed at removing passwords from source and config files.}
#   s.homepage = %q{http://wiki.yellowpages.com/display/ACH/Programmatic+Password+Encryption}
#   s.description = %q{A Crypto library that generates keys/IVs and uses these keys to generate encrypted strings stored on disk.  The keys/IVs can be shared per team so the files that are generated can be checked into SVN if necessary.}
#   s.files = ["lib/key_loader.rb", "lib/password_client.rb", "lib/password_service.rb", "test/pasword_service_test.rb"]
#   s.has_rdoc = false
#   s.test_files = ["test/password_service_test.rb"]
#end
#
#
#
#Rake::GemPackageTask.new(spec) do |pkg| 
#  pkg.need_tar = true 
#end 
