
/*
 * 
 */

package com.strongauth.strongkeylite.web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jun 14 16:10:14 PDT 2010
 * Generated source version: 2.2.9
 * 
 */


@WebServiceClient(name = "EncryptionService", 
                  wsdlLocation = "file:EncryptionService.wsdl",
                  targetNamespace = "http://web.strongkeylite.strongauth.com/") 
public class EncryptionService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://web.strongkeylite.strongauth.com/", "EncryptionService");
    public final static QName EncryptionPort = new QName("http://web.strongkeylite.strongauth.com/", "EncryptionPort");
    static {
        URL url = null;
        try {
            url = new URL("file:EncryptionService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:EncryptionService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public EncryptionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EncryptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EncryptionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns Encryption
     */
    @WebEndpoint(name = "EncryptionPort")
    public Encryption getEncryptionPort() {
        return super.getPort(EncryptionPort, Encryption.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Encryption
     */
    @WebEndpoint(name = "EncryptionPort")
    public Encryption getEncryptionPort(WebServiceFeature... features) {
        return super.getPort(EncryptionPort, Encryption.class, features);
    }

}
