
package com.strongauth.strongkeylite.web;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.9
 * Mon Jun 14 16:10:14 PDT 2010
 * Generated source version: 2.2.9
 * 
 */

@WebFault(name = "StrongKeyLiteException", targetNamespace = "http://web.strongkeylite.strongauth.com/")
public class StrongKeyLiteException_Exception extends Exception {
    public static final long serialVersionUID = 20100614161014L;
    
    private com.strongauth.strongkeylite.web.StrongKeyLiteException strongKeyLiteException;

    public StrongKeyLiteException_Exception() {
        super();
    }
    
    public StrongKeyLiteException_Exception(String message) {
        super(message);
    }
    
    public StrongKeyLiteException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public StrongKeyLiteException_Exception(String message, com.strongauth.strongkeylite.web.StrongKeyLiteException strongKeyLiteException) {
        super(message);
        this.strongKeyLiteException = strongKeyLiteException;
    }

    public StrongKeyLiteException_Exception(String message, com.strongauth.strongkeylite.web.StrongKeyLiteException strongKeyLiteException, Throwable cause) {
        super(message, cause);
        this.strongKeyLiteException = strongKeyLiteException;
    }

    public com.strongauth.strongkeylite.web.StrongKeyLiteException getFaultInfo() {
        return this.strongKeyLiteException;
    }
}
